language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t klove6502/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true klove6502/docker-react npm run test